// swift-tools-version:5.9
// PetDocs iOS — shared client kit (models + REST auth client + keychain
// session storage + deep-link parsing). The SwiftUI app target lives in
// App/ and is generated by XcodeGen (project.yml); this package keeps the
// core testable with plain `swift test` on any host.
import PackageDescription

let package = Package(
    name: "PetDocsKit",
    platforms: [
        .iOS(.v17),
        .macOS(.v14),
    ],
    products: [
        .library(name: "PetDocsKit", targets: ["PetDocsKit"]),
    ],
    targets: [
        .target(
            name: "PetDocsKit",
            path: "Sources/PetDocsKit"
        ),
        .testTarget(
            name: "PetDocsKitTests",
            dependencies: ["PetDocsKit"],
            path: "Tests/PetDocsKitTests"
        ),
    ],
    // Swift 5 language mode for now; migrating to Swift 6 strict concurrency
    // is milestone M2 in docs/ios-macos-plan.md.
    swiftLanguageVersions: [.v5]
)
